### ISSUE TITLE
small bug in map entry write8

### ISSUE THREAD

**Issue by rakslice** [Spritetm/plexus_20_emu#14]
I think there's a small bug in map entry write8,
`0xff000` should be `0xff00`, zeroing a few bits there

https://github.com/Spritetm/plexus_20_emu/blob/1283cb930d9c0ccb7e2b5505a17783305ddb6150/mapper.c#L146

**Comment by Spritetm** [comment]
Oh, thanks. I don't think it affected any of the issues we're seeing now, but it probably fixes issues we haven't ran into yet.
