### ISSUE TITLE
address off by an instruction in disassembly

### ISSUE THREAD

**Issue by rakslice** [Spritetm/plexus_20_emu#17]
The addresses this outputs for each instruction are off by an instruction because you increment `pos` to point to the next instruction before you print out the current instruction

https://github.com/Spritetm/plexus_20_emu/blob/15ec1b0935fe4b19594c518435e045b1577ecbf1/emu.c#L182

**Comment by Spritetm** [comment]
Thanks, that's probably the reason why I always felt slightly confused when using it.
